
location: D:/upLoad/club

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JavaWebBook?useUnicode=true&characterEncoding=utf8
    username: root
    password: Shangxiao111
  thymeleaf:
    prefix: classpath:/templates/book/  # 网页的存放地址
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/,classpath:/static/assets/,classpath:/static/scenicSingle/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resource/,file:${location}

